// <auto-generated/>
#pragma warning disable
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using WolverineMultiTenantExample.Services;

namespace Internal.Generated.WolverineHandlers
{
    // START: SendEmailMessageHandler1779250945
    [global::System.CodeDom.Compiler.GeneratedCode("JasperFx", "1.0.0")]
    public sealed class SendEmailMessageHandler1779250945 : Wolverine.Runtime.Handlers.MessageHandler
    {
        private readonly Microsoft.Extensions.DependencyInjection.IServiceScopeFactory _serviceScopeFactory;
        private readonly WolverineMultiTenantExample.Services.ITenantService _tenantService;
        private readonly Microsoft.Extensions.Logging.ILogger<WolverineMultiTenantExample.TenantContextMiddleware> _logger1;
        private readonly Microsoft.Extensions.Logging.ILogger<WolverineMultiTenantExample.EmailHandler> _logger2;

        public SendEmailMessageHandler1779250945(Microsoft.Extensions.DependencyInjection.IServiceScopeFactory serviceScopeFactory, WolverineMultiTenantExample.Services.ITenantService tenantService, Microsoft.Extensions.Logging.ILogger<WolverineMultiTenantExample.TenantContextMiddleware> __logger1, Microsoft.Extensions.Logging.ILogger<WolverineMultiTenantExample.EmailHandler> __logger2)
        {
            _serviceScopeFactory = serviceScopeFactory;
            _tenantService = tenantService;
            _logger1 = __logger1;
            _logger2 = __logger2;
        }



        public override async System.Threading.Tasks.Task HandleAsync(Wolverine.Runtime.MessageContext context, System.Threading.CancellationToken cancellation)
        {
            using var serviceScope = _serviceScopeFactory.CreateScope();
            
            /*
            * Using the scoped provider service location approach
            * because at least one dependency is directly using IServiceProvider or has an opaque, scoped or transient Lambda registration
            */
            var tenantContext = Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<WolverineMultiTenantExample.ITenantContext>(serviceScope.ServiceProvider);
            // The actual message body
            var sendEmailMessage = (WolverineMultiTenantExample.Models.SendEmailMessage)context.Envelope.Message;

            var tenantContextMiddleware = new WolverineMultiTenantExample.TenantContextMiddleware(tenantContext, _tenantService, _logger1);
            await tenantContextMiddleware.BeforeAsync(context).ConfigureAwait(false);
            try
            {
                System.Diagnostics.Activity.Current?.SetTag("message.handler", "WolverineMultiTenantExample.EmailHandler");
                var emailHandler = new WolverineMultiTenantExample.EmailHandler(tenantContext, serviceScope.ServiceProvider, _logger2);
                
                // The actual message execution
                await emailHandler.Handle(sendEmailMessage).ConfigureAwait(false);

            }

            finally
            {
                tenantContextMiddleware.Finally();
            }

        }

    }

    // END: SendEmailMessageHandler1779250945
    
    
}

